apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: task1-service-config
requires:
- path: ../../base
- path: ../common
build:
  artifacts:
  - image: task1
    requires:
    - image: base
      alias: BASE
    - image: common
      alias: COMMON
deploy:
  kubectl:
    manifests:
    - k8s/*