apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: detector-service-config
requires:
- path: ../base
build:
  artifacts:
  - image: detector-service
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - k8s/*