kind: Service
apiVersion: v1
metadata:
  name: task2
  labels:
    app: task2
spec:
  selector:
    app: task2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2
  labels:
    app: task2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "task2"
        dapr.io/app-port: "8080"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: service
        image: task2
        ports:
        - containerPort: 8080
